# Generated by Django 4.0.6 on 2024-02-17 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom_app', '0007_alter_product_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_rating',
            name='info',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AlterField(
            model_name='product_rating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
