# Generated by Django 4.0.6 on 2024-02-17 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom_app', '0008_product_rating_info_alter_product_rating_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='duo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.cart')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.products')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.product_rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
