# Generated by Django 4.0.6 on 2024-02-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0009_duo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='duo',
        ),
    ]
