# Generated by Django 4.0.6 on 2024-02-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0012_rename_all_all_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_1',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.products'),
        ),
    ]
