# Generated by Django 4.0.6 on 2024-02-25 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom_app', '0013_alter_all_1_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntity', models.PositiveIntegerField()),
                ('Address', models.TextField()),
                ('status', models.CharField(choices=[('ap', 'APPROVED'), ('Del', 'DELIVERD')], default='pending', max_length=100)),
                ('total_amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='all_1',
        ),
    ]
