# Generated by Django 4.0.6 on 2024-02-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0014_orders_data_delete_all_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_data',
            name='email',
            field=models.EmailField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='orders_data',
            name='fname',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='orders_data',
            name='lname',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='orders_data',
            name='mobile_no',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
