# Generated by Django 4.0.6 on 2024-02-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0015_orders_data_email_orders_data_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_data',
            name='lname',
        ),
    ]
