# Generated by Django 4.0.6 on 2024-03-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0018_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
